# Generated by Django 3.0.5 on 2020-05-25 12:48

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(max_length=15000, verbose_name='Тело комментария')),
                ('comment_date', models.DateField(default=datetime.datetime(2020, 5, 25, 12, 48, 6, 115036, tzinfo=utc), verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.CreateModel(
            name='Tred',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tred_name', models.CharField(max_length=150, verbose_name='Имя треда')),
                ('tred_content', models.TextField(max_length=15000, verbose_name='Тело треда')),
                ('tred_date', models.DateTimeField(default=datetime.datetime(2020, 5, 25, 12, 48, 6, 114035, tzinfo=utc), verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Тред',
                'verbose_name_plural': 'Треды',
            },
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
        migrations.AddField(
            model_name='comment',
            name='tred_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Tred'),
        ),
    ]
