# Generated by Django 3.0.5 on 2020-05-13 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='description',
            new_name='post_content',
        ),
        migrations.AddField(
            model_name='posts',
            name='post_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата создания'),
        ),
    ]
