# Generated by Django 3.0.5 on 2020-05-25 12:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_auto_20200525_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 12, 51, 36, 946733, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tred',
            name='tred_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 12, 51, 36, 946733, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
