# Generated by Django 3.0.5 on 2020-05-13 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_posts2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts2',
        ),
    ]
