# Generated by Django 3.0.5 on 2020-05-15 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_delete_posts2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='name',
            new_name='post_name',
        ),
    ]
