# Generated by Django 3.0.5 on 2020-05-25 13:15

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20200525_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 25, 13, 15, 18, 261974, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainpage.Comment', verbose_name='Родительский комментарий'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='tred_parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Tred', verbose_name='Родительский тред'),
        ),
        migrations.AlterField(
            model_name='tred',
            name='tred_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 25, 13, 15, 18, 260976, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
