# Generated by Django 3.0.5 on 2020-05-26 11:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_auto_20200525_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='full_path',
            field=models.TextField(blank=True, null=True, verbose_name='Полный путь'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 26, 11, 43, 53, 857525, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tred',
            name='tred_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 26, 11, 43, 53, 857525, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
