# Generated by Django 3.0.5 on 2020-05-17 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
