# Generated by Django 3.0.5 on 2020-05-17 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0008_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
