# Generated by Django 3.0.5 on 2020-05-19 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0009_delete_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(default='replace', max_length=160),
        ),
    ]
