# Generated by Django 3.0.5 on 2020-05-21 19:04

from django.db import migrations, models
import mainpage.models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0010_auto_20200519_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='url',
            field=models.SlugField(default=mainpage.models.Post.number, max_length=160, unique=True),
        ),
    ]
