# Generated by Django 3.0.5 on 2020-05-22 18:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0013_delete_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_content', models.TextField(max_length=15000, verbose_name='Тело комментария')),
                ('comment_date', models.DateField(default=datetime.date.today, verbose_name='Дата создания')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Post')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
