# Generated by Django 3.0.5 on 2020-05-22 18:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0015_remove_post_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 18, 51, 13, 722224, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
