# Generated by Django 3.0.5 on 2020-05-22 18:54

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0016_auto_20200522_2151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 22, 18, 54, 53, 860574, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 22, 18, 54, 53, 859581, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
