# Generated by Django 3.0.5 on 2020-05-24 15:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0017_auto_20200522_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='parent_id',
            new_name='tred_parent',
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 24, 15, 42, 33, 414524, tzinfo=utc), verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 15, 42, 33, 414524, tzinfo=utc), verbose_name='Дата создания'),
        ),
    ]
